#!/bin/bash

# Checking dependencies
JQ_BIN="$(whereis -b jq | awk '{print $2}')"
ROFI_BIN="$(whereis -b rofi | awk '{print $2}')"
STREAMLINK_BIN="$(whereis -b streamlink |awk '{print $2}')"

if [ -z "$JQ_BIN" ]; then
  echo "ERROR: Kappa Launcher dependency not found: jq"
  exit 1
fi
if [ -z "$ROFI_BIN" ]; then
  echo "ERROR: Kappa Launcher dependency not found: rofi"
  exit 1
fi
if [ -z "$STREAMLINK_BIN" ]; then
  echo "ERROR: Kappa Launcher dependency not found: streamlink"
  echo "If you only intend to use the browser function, you will not need this"
fi

# Some functions
_config () {
  mkdir -p $MAIN_PATH
  cat << EOF >$FILE
# Either streamlink or browser, default streamlink.
STREAM=streamlink

# Either chatterino or chatty, default chatterino. Irrelevant when using browser.
CHAT=chatterino

# Video player used. Default VLC.
PLAYER=vlc

# OAuth
OAUTH=replace_this_with_oauth_string

# Leaves current stream running when a new one is launched. Variables: true, false, ask.
MULTIPLE=true
EOF
}

_filecheck () {
  if [ -f "$FILE" ]; then
    echo "Configuration file found, proceeding"
  else
    echo "First start detected, generating configuration file"
    _config
    echo ""
    echo "Configuration file created in .config/kpl"
    echo ""
    echo "Edit it with your OAuth key (https://spheroid.xyz/kappa/) and relaunch the script"
    exit
  fi
}

_rofi () {
  rofi -dmenu -i -disable-history -scroll-method 1 "$@"
}

_launcher () {
  if [[ "$STREAM" = "streamlink" ]]; then
    if [[ "$MULTIPLE" != "true" ]]; then
      killall -9 "$PLAYER" "$CHAT" &
    fi
    streamlink --hls-live-edge=1 --player="$PLAYER" twitch.tv/$MAIN $QUALITY &
    echo "launching $STREAM"
    sleep 1
    if [[ "$CHAT" = "chatterino" ]]; then
      chatterino &
    elif [[ "$CHAT" = "chatty" ]]; then
      chatty -channel $MAIN -connect
    else
      echo "ERROR: Chat not defined in config file"
    fi
  elif [[ "$STREAM" = "browser" ]]; then
    xdg-open https://twitch.tv/$MAIN
  else
    echo "ERROR: Player not defined in config file"
  fi
  y=$(( $y + 1))
  x=$(( $x + 1))
}

_quality () {
  RESOLUTION=$(streamlink twitch.tv/$MAIN --player=none | grep -i  audio_only | cut -c 19- | tr , '\n' | tac | cut -d ' ' -f 2)
  QUALITY=$(echo "$RESOLUTION" | _rofi -theme-str 'inputbar { children: [prompt];}' \
  -no-custom -p "Select stream quality")
  if [ -z "$QUALITY" ]; then
    exit
  fi
}

_multiple () {
  if [[ "$MULTIPLE" = true ]]; then
    MULTIPLE="true"
  elif [[ "$MULTIPLE" = "ask" ]]; then
   if [[ -z $(pgrep streamlink) ]]; then
    MULTIPLE="true"
   else
    MULTIPLE=$( echo -e "true\nfalse" | _rofi -theme-str 'input { children: [prompt];}' -no-custom -p "Watch multiple streams at same time?")
   fi
  fi
}

_customdata () {
  curl -s -o $MAIN_PATH/customdata.json -H "Client-ID: 3lyhpjkzellmam3843w7eq3es84375" \
  -X GET "https://api.twitch.tv/helix/streams?user_login=$MAIN"
}

_choice () {
  if [[ "$CHOICE" = "<b>Watch now</b>" ]]; then
    _multiple
    _launcher
  elif [[ "$CHOICE" = "Choose quality (default = best)" ]]; then
    _quality
    _multiple
    _launcher
  elif [[ "$CHOICE" = "Back to Followed channels" ]]; then
    y=$(( $y + 1))
  else [ -z "$MAIN" ];
    exit
  fi
}

# Setting working directory, checking for configuration file, generating it if needed

if [ -z "$XDG_CONFIG_HOME" ]; then
  FILE=~/.config/kpl/config
  MAIN_PATH=~/.config/kpl
  _filecheck
else
  FILE=$XDG_CONFIG_HOME/kpl/config
  MAIN_PATH=$XDG_CONFIG_HOME/kpl
  _filecheck
fi

# Checking if streamlink has default-stream set to handle quality questions
if [ -z "$XDG_CONFIG_HOME" ]; then
  SL_FILE=~/.config/streamlink/config
else
  SL_FILE=$XDG_CONFIG_HOME/streamlink/config
fi

# Grab configuration file
source $MAIN_PATH/config

# Setting OAuth key, connecting to Twitch API and retrieving followed data
# This is a slightly edited version of https://github.com/begs/livestreamers/blob/master/live.py

curl -s -o $MAIN_PATH/followdata.json -H "Accept: application/vnd.twitchtv.v5+json" \
-H "Client-ID: 3lyhpjkzellmam3843w7eq3es84375" \
-H "Authorization: OAuth $OAUTH" \
-X GET "https://api.twitch.tv/kraken/streams/followed?limit=100"
curl -s -H "Accept: application/vnd.twitchtv.v5+json" \
-H "Client-ID: 3lyhpjkzellmam3843w7eq3es84375" \
-H "Authorization: OAuth $OAUTH" \
-X GET "https://api.twitch.tv/kraken/streams/followed?limit=100&offset=100" >> $MAIN_PATH/followdata.json

# Checking if json file is properly populated
if grep -q "invalid oauth token" "$MAIN_PATH/followdata.json"; then
  echo "ERROR: json file not populated, make sure you only copied your OAuth string, and not the \
  preceeding 'oauth:' section"
  exit
else
  echo "json file successfully populated"
fi

# Getting names of currently live streams
x=1
while [[ $x -le 1 ]]; do
  y=1
  if [[ -f "$SL_FILE" ]] && [[ $(grep -c ^default-stream $SL_FILE) -eq 1 ]]; then
    QUALITY=""
  else
    QUALITY=best
  fi
  STREAMS=$(jq -r '.streams[].channel.display_name' $MAIN_PATH/followdata.json)

  # Listing said streams with rofi
  MAIN=$(echo "$STREAMS" | _rofi -theme-str 'inputbar { children: [prompt,entry];}' \
  -p "Followed channels: ")

  if [[ "$STREAMS" != *"$MAIN"* ]]; then
    while [[ $y -le 1 ]]; do
      _customdata
      if grep -q "user_name" "$MAIN_PATH/customdata.json" ; then

        CHOICE=$(echo "<b>Watch now</b>
Choose quality (default = best)
Back to Followed channels" | _rofi -markup-rows -theme-str 'inputbar { children: [prompt];}' \
-p "$MAIN is live! ")

        _choice
      else
        CHOICE=$(echo "Back to Followed channels" | _rofi -theme-str \
        'inputbar { children: [prompt];}' -p "$MAIN is currently offline :( ")

        if [[ "$CHOICE" = "Back to Followed channels" ]]; then
          y=$(( $y + 1))
        else [ -z "$MAIN" ];
          exit
        fi
      fi
    done
  elif [ -z "$MAIN" ]; then
    exit
  else
    # Retrieving additional information
    CURRENT_GAME=$(jq -r ".streams[].channel | select(.display_name==\"$MAIN\") | .game"  $MAIN_PATH/followdata.json)
    STATUS=$(jq -r ".streams[].channel | select(.display_name==\"$MAIN\") | .status"  $MAIN_PATH/followdata.json)
    VIEWERS=$(jq -r ".streams[] | select(.channel.display_name==\"$MAIN\") | .viewers"  $MAIN_PATH/followdata.json)

    # Prompting with stream info and options
    while [[ $y -le 1 ]]; do
    CHOICE=$(echo "$STATUS

<b>Watch now</b>
Choose quality (default = best)
Back to Followed channels" | _rofi -theme-str 'inputbar { children: [prompt];}' \
-selected-row 2 -no-custom -markup-rows -p "$MAIN is streaming $CURRENT_GAME to $VIEWERS viewers")

    _choice
  done
  fi
done
exit
